apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: graphrag
labels:
  - pairs:
      app.kubernetes.io/part-of: graphrag
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
resources:
  - namespace.yaml
  - config.yaml
  - neo4j.yaml
  - api.yaml
  - web.yaml
  - ingest.yaml
  - middlewares.yaml
  - ingress.yaml
  - networkpolicies.yaml
images:
  - name: ghcr.io/lovichidorian/graphrag-api
    newTag: latest
  - name: ghcr.io/lovichidorian/graphrag-web
    newTag: latest
